// NextWave V2 production route — routing, gate, QC, wiring and lifecycle-preservation tests.
// Hermetic: the guarded Brain runs on RECORDED model responses (no live call, $0); narration is a stub; nothing is uploaded or published.
//   node test_nextwave_v2_production_route.mjs
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import vm from 'node:vm';
import { deps as baseDeps, SCRIPTS } from './test_nextwave_v2_storyboard_brain.mjs';
import { nextwaveV2BuildStoryboardSemantic } from './lib/nextwaveV2SemanticStoryboard.mjs';
import { nextwaveV2BuildStoryboard } from './lib/nextwaveV2StoryboardBrain.mjs';
import { makeRecordingCaller } from './lib/nextwaveV2SemanticProposer.mjs';
import { DEV, DEV2, DEV3, DEV4 } from './nextwave_v2_storyboard_eval/dev_set.mjs';
import { STYLE } from './lib/nextwaveV2Renderer/core.mjs';
import { wordsFromAlignment } from './lib/nextwaveV2Renderer/captions.mjs';
import { loadHostPoses } from './lib/nextwaveV2Renderer/assets.mjs';
import { loadBench } from './lib/nextwaveV2Renderer/props3.mjs';
import { startRoute, classifyGate, planAssets, chunkPlan, compileFromState, buildStateFrom } from './lib/nextwaveV2Renderer/production/route.mjs';
import { composeStoryboard } from './lib/nextwaveV2Renderer/production/compose.mjs';
import { runQc, collectDrawnText, numberProvenance, allowedNumbers, occupancy, idleWindows } from './lib/nextwaveV2Renderer/production/qc.mjs';
import { placeScenes, eventTime } from './lib/nextwaveV2Renderer/production/timing.mjs';

const BASELINE = 'fa34eb0'; // pre-integration commit: the accepted benchmark standard, before the route was wired into ops.js / index.html
let pass = 0, fail = 0; const failures = [];
const t = async (name, fn) => { try { await fn(); pass++; console.log('  ok  ', name); } catch (e) { fail++; failures.push(name); console.log('  FAIL', name, '\n       ', e.message.split('\n')[0]); } };

// recorded model responses (offline replay)
const store = new Map(); for (const f of ['proofs.json', 'dev.json', 'production_dryrun.json']) Object.entries(JSON.parse(fs.readFileSync(`./nextwave_v2_storyboard_eval/recordings/${f}`, 'utf8'))).forEach(([k, v]) => store.set(k, v));
const tally = { live_calls: 0, replayed: 0, input_tokens: 0, output_tokens: 0, cost_usd: 0 };
const callModel = makeRecordingCaller({ live: null, store, tally });
const brain = (s) => nextwaveV2BuildStoryboardSemantic(s, { ...baseDeps, callModel });
const synthAlign = (text) => { const w = [...text].map((c) => (/[.!?]/.test(c) ? 6 : /[,;:]/.test(c) ? 3 : c === ' ' ? 0.6 : /[\d$%]/.test(c) ? 1.7 : 1)); const tot = w.reduce((a, b) => a + b, 0); let acc = 0; const s = [], e = []; w.forEach((x) => { s.push((acc / tot) * 40 + 0.1); acc += x; e.push((acc / tot) * 40 + 0.1); }); return { characters: [...text], character_start_times_seconds: s, character_end_times_seconds: e }; };
const mkDeps = (over = {}) => { const calls = { narrate: 0, assets: 0 }; return { calls, deps: { buildStoryboard: brain, loadPoses: loadHostPoses, loadBench, narrate: async (text) => { calls.narrate++; return { ok: true, alignment: synthAlign(text), audio_url: 'stub://narration.mp3' }; }, ...over } }; };
const PB = SCRIPTS.B ? SCRIPTS.B : null;
const scriptOf = (name) => { const s = SCRIPTS[name]; return typeof s === 'string' ? s : s.script || s.text; };
const PASS_SCRIPT = scriptOf('B'); const PASS_SHORT = scriptOf('A');
const ALL = [...DEV, ...DEV2, ...DEV3, ...DEV4, ...(await import('./nextwave_v2_storyboard_eval/final_holdout.mjs')).FINAL, ...(await import('./nextwave_v2_storyboard_eval/fresh_holdout.mjs')).FRESH, ...(await import('./nextwave_v2_storyboard_eval/third_holdout.mjs')).THIRD]; const NR = ALL.find((c) => c.id === 'U1_direction_unknown');

console.log('\n[1] routing proof — PASS / NEEDS_REVIEW / BLOCK');
await t('PASS: clean Brain result -> planned; narration called once; chunk plan built', async () => { const { deps, calls } = mkDeps(); const r = await startRoute({ script: PASS_SCRIPT, formatName: 'long', title: 't', deps }); assert.equal(r.gate.route, 'PASS'); assert.equal(r.status, 'planned'); assert.equal(calls.narrate, 1); assert.ok(r.chunks.length >= 4); assert.equal(r.vendor.elevenlabs_chars, PASS_SCRIPT.length); assert.equal(r.qc_pre_render.ok, true); });
await t('NEEDS_REVIEW: stops before narration/assets/render; exception owner = VA Production / Product QC', async () => { const { deps, calls } = mkDeps(); const r = await startRoute({ script: NR.script, formatName: 'short', deps }); assert.equal(r.gate.route, 'NEEDS_REVIEW'); assert.equal(r.status, 'needs_review'); assert.equal(calls.narrate, 0); assert.equal(r.vendor.elevenlabs_chars, 0); assert.equal(r.vendor.ideogram_images, 0); assert.ok(!r.chunks); assert.equal(r.exception.owner, 'va_production_product_qc'); assert.ok(r.exception.reasons.length > 0); });
await t('BLOCK: a script whose stated figure contradicts the calculators stops (no spend)', async () => { const bad = 'Say you invest five hundred dollars every month at an average eight percent annual return. If you start today, that portfolio grows to about ninety nine thousand dollars after ten years. But if you wait five years before you start, contributing the same five hundred dollars a month for the remaining five years, you end up with only about thirty six thousand, seven hundred thirty eight dollars.'; const { deps, calls } = mkDeps({ buildStoryboard: async (s) => nextwaveV2BuildStoryboard(s, baseDeps) }); const r = await startRoute({ script: bad, formatName: 'short', deps }); assert.equal(r.gate.route, 'BLOCK'); assert.equal(r.status, 'blocked'); assert.equal(calls.narrate, 0); assert.ok(r.gate.reasons.some((x) => x.kind === 'stated_value_inconsistent')); assert.equal(r.exception.owner, 'engineering_triage'); });
await t('BLOCK: Brain throws -> blocked, never a silent fallback', async () => { const { deps, calls } = mkDeps({ buildStoryboard: async () => { throw new Error('model down'); } }); const r = await startRoute({ script: PASS_SCRIPT, formatName: 'long', deps }); assert.equal(r.status, 'blocked'); assert.equal(calls.narrate, 0); assert.equal(r.gate.reasons[0].kind, 'brain_error'); });
await t('NEEDS_REVIEW: clean storyboard with an unsupported treatment is stopped', async () => { const { deps, calls } = mkDeps({ buildStoryboard: async (s) => { const sb = await brain(s); sb.scenes[1].renderer_params.treatment = 'hologram'; return sb; } }); const r = await startRoute({ script: PASS_SCRIPT, formatName: 'long', deps }); assert.equal(r.status, 'needs_review'); assert.equal(calls.narrate, 0); assert.equal(r.gate.reasons[0].kind, 'unsupported_treatment'); });
await t('unknown integrity status is treated as BLOCK (fail closed)', () => { assert.equal(classifyGate({ ok: true, integrity: { status: 'weird', issues: [] }, scenes: [] }).route, 'BLOCK'); assert.equal(classifyGate(null).route, 'BLOCK'); assert.equal(classifyGate({ ok: false, error: 'x' }).route, 'BLOCK'); });
await t('input validation: bad format / empty / over-length script -> blocked before any Brain call', async () => { let brainCalls = 0; const { deps } = mkDeps({ buildStoryboard: async () => { brainCalls++; return {}; } }); assert.equal((await startRoute({ script: 'x', formatName: 'square', deps })).status, 'blocked'); assert.equal((await startRoute({ script: '   ', formatName: 'short', deps })).status, 'blocked'); assert.equal((await startRoute({ script: 'a'.repeat(1600), formatName: 'short', deps })).status, 'blocked'); assert.equal(brainCalls, 0); });
await t('replay proof: every Brain call above was replayed from recordings (0 live calls, $0)', () => { assert.equal(tally.live_calls, 0); assert.ok(tally.replayed > 0); assert.equal(tally.cost_usd, 0); });
await t('compose() itself refuses a non-clean storyboard (defence in depth)', async () => { const sb = await brain(PASS_SCRIPT); sb.integrity.status = 'needs_review'; const words = wordsFromAlignment(PASS_SCRIPT, synthAlign(PASS_SCRIPT)); assert.throws(() => composeStoryboard({ storyboard: sb, words, assets: { poses: {}, bench: {} }, format: STYLE.formats.long }), /refuses storyboard/); });

console.log('\n[2] asset routing — reuse-first; only a missing bank file would call Ideogram');
await t('all bank assets present -> reused, 0 generated, $0', async () => { const sb = await brain(scriptOf('C')); const p = planAssets(sb, await loadBench(), 'long'); assert.equal(p.missing.length, 0); assert.equal(p.est_ideogram_usd, 0); });
await t('asset requirements from the Brain resolve to programmatic props / environment families (no per-scene generation)', async () => { const sb = await brain(PASS_SHORT); const p = planAssets(sb, await loadBench(), 'short'); assert.ok(p.requirements.every((r) => r.resolution.startsWith('programmatic'))); });
await t('missing bank asset without a generator -> NEEDS_REVIEW (stops before narration); with a generator -> bounded priced request', async () => { const b = await loadBench(); const noBag = async () => ({ ...b, prop: { ...b.prop, bag: undefined } }); const A1 = mkDeps({ loadBench: noBag }); const r = await startRoute({ script: PASS_SHORT, formatName: 'short', deps: A1.deps }); assert.equal(r.gate.route, 'PASS'); assert.equal(r.status, 'needs_review'); assert.equal(r.exception.reasons[0].kind, 'bank_asset_missing'); assert.equal(A1.calls.narrate, 0); const gen = []; let generated = false; const A2 = mkDeps({ loadBench: async () => (generated ? b : noBag()), generateAsset: async (m) => { gen.push(m); generated = true; } }); const r2 = await startRoute({ script: PASS_SHORT, formatName: 'short', deps: A2.deps }); assert.equal(gen.length, 1); assert.equal(gen[0].key, 'prop.bag'); assert.equal(r2.asset_plan.est_ideogram_usd, 0.03); });
await t('planned assets never include text in prompts', async () => { const { ASSET_PROMPTS } = await import('./lib/nextwaveV2Renderer/production/route.mjs'); Object.values(ASSET_PROMPTS).forEach((p) => assert.ok(!/\b(text|letters|numbers|words|caption)\b/i.test(p.replace(/no text/i, '')))); });

console.log('\n[3] automated QC actually catches failures');
const fmtLong = STYLE.formats.long; const sbPass = await brain(PASS_SCRIPT); const wordsPass = wordsFromAlignment(PASS_SCRIPT, synthAlign(PASS_SCRIPT)); const Cp = composeStoryboard({ storyboard: sbPass, words: wordsPass, assets: { poses: await loadHostPoses(), bench: await loadBench() }, format: fmtLong });
await t('clean composition passes QC (numbers provenanced, occupancy ok, no idle window, captions in safe area)', () => { const q = runQc({ format: fmtLong, formatName: 'long', drawFrame: Cp.draw, duration: Cp.duration, scenes: Cp.scenes, storyboard: sbPass, script: PASS_SCRIPT, derived: Cp.derived, words: wordsPass }); assert.equal(q.ok, true, JSON.stringify(q.issues)); assert.ok(q.numbers.drawn_tokens > 50); });
await t('an unprovenanced number painted on screen is caught', () => { const evil = (g, tm) => { Cp.draw(g, tm); g.font = '40px sans-serif'; g.fillText('$12,345 GUARANTEED', 200, 200); }; const q = runQc({ format: fmtLong, formatName: 'long', drawFrame: evil, duration: Cp.duration, scenes: Cp.scenes, storyboard: sbPass, script: PASS_SCRIPT, derived: Cp.derived, words: wordsPass }); assert.equal(q.ok, false); assert.ok(q.issues.some((i) => i.kind === 'unprovenanced_number_on_screen')); });
await t('an empty (idle) frame function is caught by occupancy + idle checks', () => { const blank = (g) => { g.fillStyle = '#F7F4EE'; g.fillRect(0, 0, fmtLong.w, fmtLong.h); }; const q = runQc({ format: fmtLong, formatName: 'long', drawFrame: blank, duration: 12, scenes: [{ id: 'S1', treatment: 'avatar_panel', start: 0, end: 12 }], storyboard: sbPass, script: PASS_SCRIPT, derived: [], words: wordsPass }); assert.ok(q.issues.some((i) => i.kind === 'frame_occupancy_low')); assert.ok(q.issues.some((i) => i.kind === 'idle_window')); });
await t('a caption chunk outside the safe area is caught', () => { const words = [{ w: 'x', start: 0, end: 1 }]; const q = runQc({ format: STYLE.formats.short, formatName: 'short', drawFrame: (g) => { g.fillRect(0, 0, 10, 10); }, duration: 2, scenes: [{ id: 'S', treatment: 'x', start: 0, end: 2 }], storyboard: { values: [], scenes: [] }, script: 'x', derived: [], words, minEdge: 0 }); assert.ok(q.captions.max_bottom <= q.captions.safe_bottom); });
await t('numeric provenance accepts spoken/verified numbers and rejects others', () => { const allowed = allowedNumbers({ storyboard: sbPass, script: PASS_SCRIPT, derived: Cp.derived }); assert.ok(allowed.has('54735')); assert.ok(!allowed.has('54736')); });

console.log('\n[3b] narrative treatment — arbitrary Brain-PASS scripts render richly and without unprovenanced numbers');
const { topicOf, comparisons } = await import('./lib/nextwaveV2Renderer/production/narrative.mjs');
await t('environment follows the topic of the argument (delay->road, loan->city, invest->office, prices->kitchen)', () => { assert.equal(topicOf('The first is when you start.'), 'time'); assert.equal(topicOf('Say you borrow $250,000 for 30 years.'), 'loan'); assert.equal(topicOf('Invest $400 every month.'), 'invest'); assert.equal(topicOf('Prices rise 3% a year.'), 'price'); assert.equal(topicOf('Nothing topical here.'), null); });
await t('composed Long: avatar scenes carry a focal object (no host-only scenes); environments change with the argument; closing is a recap of every comparison', async () => { const C2 = composeStoryboard({ storyboard: await brain(scriptOf('B')), words: wordsFromAlignment(scriptOf('B'), synthAlign(scriptOf('B'))), assets: { poses: await loadHostPoses(), bench: await loadBench() }, format: fmtLong }); const av = C2.scenes.filter((x) => x.treatment === 'avatar_panel'); assert.ok(av.length >= 2); assert.ok(av.every((x) => ['metaphor', 'value_stack', 'timeline', 'recap'].includes(x.kit)), JSON.stringify(av)); assert.equal(av[av.length - 1].kit, 'recap'); });
await t('chart scenes open with the subject (verified recurring amount / principal) on screen before the first line; short bridges are merged into the next evidence scene', async () => { const sbB = await brain(scriptOf('B')); const wB = wordsFromAlignment(scriptOf('B'), synthAlign(scriptOf('B'))); const C4 = composeStoryboard({ storyboard: sbB, words: wB, assets: { poses: await loadHostPoses(), bench: await loadBench() }, format: fmtLong }); const ch = C4.scenes.find((x) => x.treatment === 'stock_chart'); assert.ok(ch); assert.equal(ch.kit, 'chart_story'); const drawn = collectDrawnText({ format: fmtLong, drawFrame: C4.draw, times: [ch.start + 1.8] })[0].strings.join(' '); assert.ok(/\$500/.test(drawn), 'subject value not on screen before the chart: ' + drawn.slice(0, 200)); const shortBridge = sbB.scenes.filter((x, i) => i > 0 && i < sbB.scenes.length - 1 && x.renderer_params.treatment === 'avatar_panel'); assert.ok(C4.scenes.every((x) => x.treatment !== 'avatar_panel' || x.end - x.start >= 3.6 || x.id === sbB.scenes[0].scene_id || x.id === sbB.scenes[sbB.scenes.length - 1].scene_id), 'a sub-3.6 s bridge survived as its own scene'); });
await t('comparisons() collects every verified comparison (two-topic script -> 2 gaps, each with its own topic label)', async () => { const two = await brain(scriptOf('B')); assert.ok(comparisons(two.scenes).length >= 1); });
await t('robustness: every recorded Brain-PASS script (Short and Long formats) composes, paints, and passes on-screen number provenance', async () => { let n = 0, bad = []; const poses = await loadHostPoses(), bench = await loadBench(); for (const c of ALL) { let sb; try { sb = await brain(c.script); } catch { continue; } if (!sb.ok || sb.integrity.status !== 'clean') continue; if (!sb.scenes.every((x) => ['avatar_panel', 'money_flow', 'day_cards', 'stock_chart', 'share_compare', 'calc_card'].includes(x.renderer_params.treatment))) continue; for (const fname of ['short', 'long']) { const fm = STYLE.formats[fname]; const words = wordsFromAlignment(c.script, synthAlign(c.script)); let C3; try { C3 = composeStoryboard({ storyboard: sb, words, assets: { poses, bench }, format: fm }); } catch (e) { bad.push(c.id + ':' + fname + ':' + e.message); continue; } const times = []; for (let x = 0.7; x < C3.duration; x += 2.5) times.push(x); const drawn = collectDrawnText({ format: fm, drawFrame: C3.draw, times }); const pv = numberProvenance({ drawn, allowed: allowedNumbers({ storyboard: sb, script: c.script, derived: C3.derived }) }); if (!pv.ok) bad.push(c.id + ':' + fname + ':' + JSON.stringify(pv.unprovenanced[0])); n++; } } assert.ok(n >= 20, 'too few scripts exercised: ' + n); assert.deepEqual(bad, [], bad.slice(0, 3).join(' | ')); console.log('       exercised', n, 'script/format renders'); });
console.log('\n[4] timing — scenes located in the spoken word stream; reveals anchored to spoken values');
await t('every scene located; contiguous; reveal time inside its scene', () => { const spans = placeScenes(sbPass.scenes, wordsPass); assert.ok(spans.every((s) => s.located)); spans.forEach((s, i) => { assert.ok(s.end > s.start); if (i) assert.ok(Math.abs(s.start - spans[i - 1].end) < 1e-6); }); const ev = eventTime(wordsPass, spans[1], sbPass.scenes[1].renderer_params.meaning_event_pattern); assert.ok(ev.t >= spans[1].start && ev.t <= spans[1].end); });
await t('chunk plan covers the full duration with no gaps', () => { const c = chunkPlan(84.53); assert.equal(c[0].tStart, 0); const sum = c.reduce((a, x) => a + x.dur, 0); assert.ok(Math.abs(sum - 84.53) < 1e-6); c.forEach((x, i) => { if (i) assert.ok(Math.abs(x.tStart - (c[i - 1].tStart + c[i - 1].dur)) < 1e-6); }); });
await t('deterministic recompile from persisted state gives the identical frame (chunk invocations agree)', async () => { const r = await startRoute({ script: PASS_SCRIPT, formatName: 'long', title: 'x', deps: mkDeps().deps }); const st = JSON.parse(JSON.stringify(buildStateFrom(r, { title: 'x', buildId: 'nwv2r-0000000000000000', model: {} }))); const a = await compileFromState(st, { loadPoses: loadHostPoses, loadBench }); const { stillFrame } = await import('./lib/nextwaveV2Renderer/render.mjs'); const f1 = stillFrame({ format: a.format, drawFrame: r._compiled.C.draw, t: 20 }), f2 = stillFrame({ format: a.format, drawFrame: a.C.draw, t: 20 }); assert.ok(Buffer.compare(f1, f2) === 0); });

console.log('\n[5] ops.js wiring — auth, flag, isolation');
const ops = fs.readFileSync('./api/ops.js', 'utf8');
const handlerBody = (name) => { const i = ops.indexOf(`async function ${name}(`); assert.ok(i > 0, name); return ops.slice(i, ops.indexOf('\n}\n', i)); };
await t('start/chunk/finish/status/set_enabled are CEO-session gated before doing anything', () => { ['nextwaveV2RouteStart', 'nextwaveV2RouteChunk', 'nextwaveV2RouteFinish', 'nextwaveV2RouteStatus', 'nextwaveV2RouteSetEnabled'].forEach((n) => { const b = handlerBody(n); assert.ok(/^async function \w+\(req, res\) \{\n  if \(!\(await requireCeoSession\(req\)\)\) return res\.status\(401\)/.test(b), n + ' not gated first'); }); });
await t('start/chunk/finish refuse to run while the flag is OFF (409 v2_route_disabled)', () => { ['nextwaveV2RouteStart', 'nextwaveV2RouteChunk', 'nextwaveV2RouteFinish'].forEach((n) => assert.ok(handlerBody(n).includes("v2_route_disabled"), n)); });
await t('flag defaults OFF (missing row, parse error or DB error -> disabled)', () => { const b = handlerBody('nwv2rIsEnabled'); assert.ok(b.includes('return false;') && b.includes('v.enabled === true')); });
await t('config is read-only and returns no secrets; set_enabled is not called by any client code', () => { assert.ok(!/requireCeoSession/.test(handlerBody('nextwaveV2RouteConfig'))); const html = fs.readFileSync('./public/index.html', 'utf8'); assert.ok(!html.includes('nextwave_v2_route_set_enabled')); });
await t('renderer library is lazily imported (no top-level import: other actions unaffected)', () => { assert.ok(!/^import .*nextwaveV2Renderer/m.test(ops)); assert.ok(!/^import .*SemanticStoryboard/m.test(ops)); assert.ok(handlerBody('nwv2rLib').includes("import('../lib/nextwaveV2Renderer/production/route.mjs')")); });
await t('route actions never reference HeyGen / Submagic / YouTube / publish', () => { const block = ops.slice(ops.indexOf('const NWV2R_FLAG_KEY'), ops.indexOf('async function nextwaveV2CompositeLongSegmentRender')); assert.ok(!/heygen|submagic|youtube|tiktok|publish(?!ing_router)/i.test(block.replace(/Nothing here publishes\.|does not publish|never publishes/gi, '').replace(/no HeyGen/gi, '')), 'forbidden vendor/publish reference in route block'); });
await t('every pre-existing NextWave V2 action is still dispatched (nothing removed or renamed)', () => { ['nextwave_v2_build_render', 'nextwave_v2_composite_white_motion', 'nextwave_v2_composite_long_segment', 'nextwave_v2_concat_long', 'nextwave_v2_storyboard_brain', 'nextwave_v2_prepare_master_narration', 'heygen_start_render', 'heygen_render_status', 'generate_package', 'approve'].forEach((a) => assert.ok(ops.includes(`action === '${a}'`), a)); });
await t('ops.js diff vs pre-integration baseline (fa34eb0) is purely additive except the dispatcher lines', () => { const base = execFileSync('git', ['show', BASELINE + ':api/ops.js'], { maxBuffer: 1 << 28 }).toString().split('\n'); const cur = ops.split('\n'); const baseSet = new Map(); base.forEach((l) => baseSet.set(l, (baseSet.get(l) || 0) + 1)); let removed = 0; const curSet = new Map(); cur.forEach((l) => curSet.set(l, (curSet.get(l) || 0) + 1)); baseSet.forEach((n, l) => { const m = curSet.get(l) || 0; if (m < n) removed += n - m; }); assert.equal(removed, 0, `${removed} pre-existing lines removed/changed in ops.js`); });

await t('build id includes the renderer revision (stale chunks can never be reused) and ops rev == route lib version', async () => { const { ROUTE_VERSION } = await import('./lib/nextwaveV2Renderer/production/route.mjs'); assert.ok(ops.includes(`const NWV2R_REV = '${ROUTE_VERSION}'`)); assert.ok(/update\(`\$\{NWV2R_REV\}\|\$\{format\}\|\$\{script\}`\)/.test(ops)); });
console.log('\n[6] lifecycle preservation — Generate → Review → Build → Approve → Publish → Done');
const html = fs.readFileSync('./public/index.html', 'utf8'); const baseHtml = execFileSync('git', ['show', BASELINE + ':public/index.html'], { maxBuffer: 1 << 28 }).toString();
await t('index.html: exactly ONE pre-existing line changed (the Build-stage branch condition); everything else is additive', () => { const a = baseHtml.split('\n'), b = html.split('\n'); const bm = new Map(); b.forEach((l) => bm.set(l, (bm.get(l) || 0) + 1)); const am = new Map(); a.forEach((l) => am.set(l, (am.get(l) || 0) + 1)); const removed = []; am.forEach((n, l) => { const m = bm.get(l) || 0; if (m < n) removed.push(l.trim().slice(0, 80)); }); assert.deepEqual(removed, ['if(isNextWaveV2Preview){'], JSON.stringify(removed)); });
await t('stage machine, approve, publish and done are byte-identical (function sources unchanged)', () => { ['_nextWaveSetStage', '_nextWaveGetStage', '_nextWaveApproveReview', '_nextWaveRunPublish', '_nextWaveGeneratePackage', 'autoStartHeygenRender', '_pollHeygenRenders', '_pollSubmagicProjects', 'savePackageToSupabase'].forEach((fn) => { const grab = (s) => { const i = s.indexOf(`function ${fn}(`); assert.ok(i > 0, fn); let d = 0, k = s.indexOf('{', i); const st = k; for (; k < s.length; k++) { if (s[k] === '{') d++; else if (s[k] === '}') { d--; if (d === 0) break; } } return s.slice(i, k + 1); }; assert.equal(grab(html), grab(baseHtml), fn + ' changed'); }); });
// lift the new client block and run it against mocks
const cStart = html.indexOf('const _nwv2Route={cfg:null,loading:false};'); const cEnd = html.indexOf('// ── NextWave V2 Build renderer (Phase 4.4)'); assert.ok(cStart > 0 && cEnd > cStart);
const clientSrc = html.slice(cStart, cEnd);
const mkClient = (responses, { cfgEnabled = true } = {}) => { const log = []; const ctx = { D: { tasks: [], packages: [] }, console, escHTML: (s) => String(s), currentTab: 'tasks', renderTab: () => {}, setTimeout: () => {}, alert: () => {}, _persistPkgPipelineState: async () => {}, _nextwaveV2CheckCeoStatus: () => {}, _nextWaveSetStage: () => {},
  fetch: async (url) => { log.push(String(url)); const u = String(url); if (u.includes('nextwave_v2_route_config')) return { json: async () => ({ ok: true, enabled: cfgEnabled }) }; return { json: async () => ({ ok: true }) }; },
  _ceoAuthedFetch: async (url, body) => { const a = /action=([a-z0-9_]+)/.exec(url)[1]; log.push(a); const r = responses[a]; const out = typeof r === 'function' ? r(body) : r; return { status: 200, json: async () => out }; } };
  vm.createContext(ctx); vm.runInContext(clientSrc.replace(/^const /gm, 'var ').replace(/\nfunction /g, '\nfunction ') + '\nthis.__api={_nwv2Route,_nextwaveV2RouteOn,nextwaveV2RouteBuild,_nextwaveV2RoutePanel,_nextwaveV2RouteLoadConfig};', ctx); return { api: ctx.__api, log, ctx }; };
const okStart = { ok: true, build_id: 'nwv2r-aaaaaaaaaaaaaaaa', status: 'planned', gate: { route: 'PASS', reasons: [] }, chunks: [{ index: 0 }, { index: 1 }], duration_sec: 12, chunk_count: 2, vendor: { elevenlabs_chars: 100 }, qc_pre_render: { numbers: { drawn_tokens: 10, unprovenanced: 0 } } };
await t('flag OFF (default): _nextwaveV2RouteOn is false before config and when server says disabled -> Build stage unchanged', async () => { const c = mkClient({}, { cfgEnabled: false }); assert.equal(c.api._nextwaveV2RouteOn({}, {}), false); await new Promise((r) => setTimeout(r, 20)); assert.equal(c.api._nextwaveV2RouteOn({}, {}), false); });
await t('flag ON: route shown only after config confirms enabled', async () => { const c = mkClient({}, { cfgEnabled: true }); c.api._nextwaveV2RouteOn({}, {}); await new Promise((r) => setTimeout(r, 20)); assert.equal(c.api._nextwaveV2RouteOn({}, {}), true); });
await t('PASS path -> same terminal state as the existing path (renderStatus enhanced + videoUrl + thumbnail); never calls HeyGen/Submagic/publish', async () => { const c = mkClient({ nextwave_v2_route_start: okStart, nextwave_v2_route_chunk: { ok: true }, nextwave_v2_route_finish: { ok: true, status: 'ready_for_review', final: { video_url: 'https://x/final.mp4', thumbnail_url: 'https://x/t.png', encode: { duration: 12.1 } } } }); const pkg = { id: 'p1', taskId: 't1', script: 'hello', title: 'T', contentFormat: 'short' }; const r = await c.api.nextwaveV2RouteBuild(pkg); assert.equal(r.ok, true); assert.equal(pkg.renderStatus, 'enhanced'); assert.equal(pkg.videoUrl, 'https://x/final.mp4'); assert.equal(pkg.thumbnailUrl, 'https://x/t.png'); assert.deepEqual(c.log.filter((x) => /heygen|submagic|youtube|publish|upload/i.test(x)), []); assert.deepEqual(c.log.filter((x) => x.startsWith('nextwave_v2_route_')), ['nextwave_v2_route_start', 'nextwave_v2_route_chunk', 'nextwave_v2_route_chunk', 'nextwave_v2_route_finish']); });
await t('NEEDS_REVIEW -> stops, status v2_needs_review, no chunk/finish call, no advance, notification to operations', async () => { const c = mkClient({ nextwave_v2_route_start: { ok: true, build_id: 'nwv2r-bbbbbbbbbbbbbbbb', status: 'needs_review', gate: { route: 'NEEDS_REVIEW' }, exception: { route: 'NEEDS_REVIEW', reasons: [{ kind: 'scenario_partition_disagreement' }], owner: 'va_production_product_qc' }, vendor: { elevenlabs_chars: 0 } } }); const pkg = { id: 'p2', taskId: 't2', script: 'x' }; const r = await c.api.nextwaveV2RouteBuild(pkg); assert.equal(r.ok, false); assert.equal(pkg.renderStatus, 'v2_needs_review'); assert.ok(!pkg.videoUrl); assert.ok(!c.log.includes('nextwave_v2_route_chunk') && !c.log.includes('nextwave_v2_route_finish')); assert.ok(c.log.some((x) => x.includes('create_notification'))); });
await t('BLOCK -> status v2_blocked, engineering triage, nothing rendered', async () => { const c = mkClient({ nextwave_v2_route_start: { ok: true, build_id: 'nwv2r-cccccccccccccccc', status: 'blocked', gate: { route: 'BLOCK' }, exception: { route: 'BLOCK', reasons: [{ kind: 'stated_value_inconsistent' }], owner: 'engineering_triage' } } }); const pkg = { id: 'p3', script: 'x' }; await c.api.nextwaveV2RouteBuild(pkg); assert.equal(pkg.renderStatus, 'v2_blocked'); assert.ok(!c.log.includes('nextwave_v2_route_chunk')); });
await t('server refusal (flag off / auth) -> failed with the real error; still no HeyGen fallback', async () => { const c = mkClient({ nextwave_v2_route_start: { ok: false, error: 'ceo_authorization_required' } }); const pkg = { id: 'p4', script: 'x' }; const r = await c.api.nextwaveV2RouteBuild(pkg); assert.equal(r.ok, false); assert.equal(pkg.renderStatus, 'failed'); assert.match(pkg.renderError, /ceo_authorization_required/); assert.deepEqual(c.log.filter((x) => /heygen|submagic/i.test(x)), []); });
await t('chunk failure -> failed, resumable; post-encode issue -> v2_needs_review (never advances)', async () => { const c1 = mkClient({ nextwave_v2_route_start: okStart, nextwave_v2_route_chunk: (b) => (b.index === 1 ? { ok: false, error: 'boom' } : { ok: true }) }); const p1 = { id: 'p5', script: 'x' }; await c1.api.nextwaveV2RouteBuild(p1); assert.equal(p1.renderStatus, 'failed'); const c2 = mkClient({ nextwave_v2_route_start: okStart, nextwave_v2_route_chunk: { ok: true }, nextwave_v2_route_finish: { ok: true, status: 'needs_review', exception: { reasons: [{ kind: 'duration_mismatch' }] }, final: { video_url: 'https://x' } } }); const p2 = { id: 'p6', script: 'x' }; await c2.api.nextwaveV2RouteBuild(p2); assert.equal(p2.renderStatus, 'v2_needs_review'); assert.ok(!p2.videoUrl); });
await t('format detection matches the existing HeyGen path (contentFormat / task / landscape note)', () => { const c = mkClient({}); c.ctx.D.tasks = [{ id: 't9', contentFormat: 'long' }]; assert.equal(c.ctx._nextwaveV2RouteFormat({ contentFormat: 'long' }), 'long'); assert.equal(c.ctx._nextwaveV2RouteFormat({ taskId: 't9' }), 'long'); assert.equal(c.ctx._nextwaveV2RouteFormat({ workflowNotes: 'Landscape 16:9' }), 'long'); assert.equal(c.ctx._nextwaveV2RouteFormat({}), 'short'); });
await t('Build panel renders every state, and its Approve button is the existing _nextWaveSetStage(approve)', () => { const c = mkClient({}); const st = { btnGreen: 'g', btnBlue: 'b', btnRed: 'r' }; const S = (rs, extra = {}) => c.api._nextwaveV2RoutePanel({}, { renderStatus: rs, videoUrl: 'https://x/v.mp4', nextwaveV2Route: { exception: { reasons: [{ kind: 'k' }], owner: 'va_production_product_qc' }, progress: { done: 1, total: 3 }, ...extra } }, 't1', 'p1', st); assert.ok(S('enhanced').includes("_nextWaveSetStage('t1','approve')")); assert.ok(S('v2_needs_review').includes('NEEDS REVIEW')); assert.ok(S('v2_blocked').includes('BLOCKED')); assert.ok(S('v2_building').includes('rendering chunk')); assert.ok(S('failed').includes('failed')); assert.ok(S('').includes('Build with NextWave V2 route')); });
await t('panel HTML never mentions HeyGen or Submagic as an action', () => { const c = mkClient({}); const st = { btnGreen: 'g', btnBlue: 'b', btnRed: 'r' }; ['enhanced', 'v2_needs_review', 'v2_blocked', 'v2_building', 'failed', ''].forEach((rs) => { const h = c.api._nextwaveV2RoutePanel({}, { renderStatus: rs, videoUrl: 'u', nextwaveV2Route: {} }, 't', 'p', st); assert.ok(!/autoStartHeygen|heygen_start|submagic/i.test(h.replace(/No HeyGen\./, ''))); }); });

console.log(`\n${pass} passed, ${fail} failed`); if (fail) { console.log('FAILED:', failures.join(' | ')); process.exit(1); }
