// End-to-end proof of the SERVERLESS wiring: the real api/ops.js handler, real route library, real ffmpeg/canvas rendering —
// with every network dependency mocked (Supabase REST + storage, ElevenLabs, Anthropic replayed from recordings). No vendor calls,
// no spend, nothing published.   node test_nextwave_v2_route_ops_e2e.mjs
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash, createHmac } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { SCRIPTS } from './test_nextwave_v2_storyboard_brain.mjs';
import { MODEL_ID } from './lib/nextwaveV2SemanticProposer.mjs';

const SECRET = 'test-secret-not-a-real-credential'; const store = new Map(); const objects = new Map(); const settings = new Map(); const calls = { eleven: 0, anthropic: 0, storagePut: 0, heygen: 0, other: [] };
for (const f of ['proofs.json', 'production_dryrun.json']) Object.entries(JSON.parse(fs.readFileSync(`./nextwave_v2_storyboard_eval/recordings/${f}`, 'utf8'))).forEach(([k, v]) => store.set(k, v));
const FF = (await import('@ffmpeg-installer/ffmpeg')).default.path;
const silentMp3 = (sec) => { const p = `/tmp/nwv2e2e-${Date.now()}.mp3`; spawnSync(FF, ['-y', '-f', 'lavfi', '-i', 'anullsrc=r=44100:cl=mono', '-t', String(sec), '-b:a', '64k', p]); const b = fs.readFileSync(p); fs.unlinkSync(p); return b; };
const synthAlign = (text) => { const w = [...text].map((c) => (/[.!?]/.test(c) ? 6 : /[,;:]/.test(c) ? 3 : c === ' ' ? 0.6 : /[\d$%]/.test(c) ? 1.7 : 1)); const tot = w.reduce((a, b) => a + b, 0); const dur = Math.max(6, text.length / 14.5); let acc = 0; const s = [], e = []; w.forEach((x) => { s.push((acc / tot) * dur + 0.1); acc += x; e.push((acc / tot) * dur + 0.1); }); return { characters: [...text], character_start_times_seconds: s, character_end_times_seconds: e, dur }; };
const json = (o, status = 200) => ({ ok: status < 400, status, headers: new Map([['content-type', 'application/json']]), json: async () => o, text: async () => JSON.stringify(o) });
globalThis.fetch = async (url, opts = {}) => {
  const u = String(url), m = (opts.method || 'GET').toUpperCase();
  if (u.includes('/rest/v1/ceo_auth_config')) return json([{ key: 'ceo_session_secret_production', value: SECRET }, { key: 'ceo_pin_hash_production', value: 'x' }]);
  if (u.includes('/rest/v1/app_settings')) { const km = /key=eq\.([^&]+)/.exec(u); const k = km ? km[1] : null; if (m === 'GET') return json(settings.has(k) ? [{ value: settings.get(k) }] : []); if (m === 'POST') { const b = JSON.parse(opts.body); settings.set(b.key, b.value); return json([b]); } if (m === 'PATCH') { settings.set(k, JSON.parse(opts.body).value); return json([{}]); } }
  if (u.includes('/storage/v1/object/srv-assets/') && m === 'POST') { const ctype = (opts.headers || {})['Content-Type']; if (ctype === 'application/json' || ctype === 'application/octet-stream' || ctype === 'text/plain') return { ok: false, status: 400, headers: new Map(), text: async () => '{"statusCode":"415","error":"invalid_mime_type"}', json: async () => ({}) }; // real bucket rejects json/octet-stream (found in preview)
   calls.storagePut++; objects.set(u.split('/srv-assets/')[1], Buffer.from(opts.body)); return json({}); }
  if (u.includes('/storage/v1/object/public/srv-assets/')) { const key = u.split('/srv-assets/')[1].split('?')[0]; const o = objects.get(key); if (!o) return { ok: false, status: 404, headers: new Map(), text: async () => 'nf', json: async () => ({}) }; const ct = key.endsWith('.json') ? 'application/json' : key.endsWith('.mp3') ? 'audio/mpeg' : key.endsWith('.png') ? 'image/png' : 'video/mp4'; return { ok: true, status: 200, headers: { get: (h) => (h.toLowerCase() === 'content-length' ? String(o.length) : h.toLowerCase() === 'content-type' ? ct : null) }, arrayBuffer: async () => o.buffer.slice(o.byteOffset, o.byteOffset + o.length), json: async () => JSON.parse(o.toString()), text: async () => o.toString() }; }
  if (u.includes('api.elevenlabs.io')) { calls.eleven++; const text = JSON.parse(opts.body).text; const a = synthAlign(text); const { dur, ...al } = a; return json({ audio_base64: silentMp3(Math.ceil(dur + 2)).toString('base64'), alignment: al }); }
  if (u.includes('api.anthropic.com')) { calls.anthropic++; const b = JSON.parse(opts.body); const key = createHash('sha256').update(MODEL_ID + '\n' + b.system + '\n' + b.messages[0].content).digest('hex'); const hit = store.get(key); if (!hit) return json({ error: { message: 'no recording' } }, 500); return json({ content: [{ text: hit.text }], usage: hit.usage || {}, model: MODEL_ID }); }
  if (/heygen|submagic/i.test(u)) calls.heygen++;
  calls.other.push(u.slice(0, 90)); return json({}, 404);
};
process.env.SUPABASE_SERVICE_KEY = 'svc-test'; process.env.SUPABASE_URL = 'https://supabase.test'; process.env.ELEVENLABS_API_KEY = 'el-test'; process.env.ANTHROPIC_API_KEY = 'an-test';
const mod = await import('./api/ops.js'); const handler = mod.default;
const token = (() => { const payload = Buffer.from(JSON.stringify({ sub: 'ceo', exp: Date.now() + 3600e3 })).toString('base64url'); return `${payload}.${createHmac('sha256', SECRET).update(payload).digest('base64url')}`; })();
const call = async (action, body, { auth = true, method = 'POST' } = {}) => { const res = { code: 200, body: null, status(c) { this.code = c; return this; }, json(b) { this.body = b; return this; }, setHeader() {}, end() {} }; const req = { method, query: { action }, body: method === 'POST' ? { ...(body || {}), ...(auth ? { ceo_session_token: token } : {}) } : undefined, headers: {} }; await handler(req, res); return res; };

let pass = 0, fail = 0; const t = async (n, f) => { try { await f(); pass++; console.log('  ok  ', n); } catch (e) { fail++; console.log('  FAIL', n, '\n       ', String(e.message).split('\n')[0]); } };
const SHORT = SCRIPTS.A, LONG = SCRIPTS.B;

console.log('\n[flag + auth]');
await t('config: flag defaults OFF; no auth needed; no secrets in the response', async () => { const r = await call('nextwave_v2_route_config', null, { method: 'GET', auth: false }); assert.equal(r.code, 200); assert.equal(r.body.enabled, false); assert.ok(!/key|secret|token/i.test(JSON.stringify(r.body).replace('route_version', ''))); });
await t('start with flag OFF -> 409 v2_route_disabled, zero vendor calls', async () => { const r = await call('nextwave_v2_route_start', { script: SHORT, format: 'short' }); assert.equal(r.code, 409); assert.equal(r.body.error, 'v2_route_disabled'); assert.equal(calls.eleven + calls.anthropic, 0); });
await t('start / chunk / finish / status / set_enabled without a CEO session -> 401, zero vendor calls', async () => { for (const a of ['nextwave_v2_route_start', 'nextwave_v2_route_chunk', 'nextwave_v2_route_finish', 'nextwave_v2_route_status', 'nextwave_v2_route_set_enabled']) { const r = await call(a, { script: SHORT, format: 'short', build_id: 'nwv2r-0000000000000000', index: 0, enabled: true }, { auth: false }); assert.equal(r.code, 401, a); } assert.equal(calls.eleven + calls.anthropic, 0); });
await t('an expired / forged session token is rejected', async () => { const forged = `${Buffer.from(JSON.stringify({ sub: 'ceo', exp: Date.now() + 1e6 })).toString('base64url')}.AAAA`; const res = { code: 0, status(c) { this.code = c; return this; }, json() { return this; }, setHeader() {}, end() {} }; await handler({ method: 'POST', query: { action: 'nextwave_v2_route_start' }, body: { script: SHORT, format: 'short', ceo_session_token: forged }, headers: {} }, res); assert.equal(res.code, 401); });
await t('production guard: even with the shared flag row ON, VERCEL_ENV=production keeps the route OFF and hides the probe', async () => { const old = process.env.VERCEL_ENV; process.env.VERCEL_ENV = 'production'; try { await call('nextwave_v2_route_set_enabled', { enabled: true }); const c = await call('nextwave_v2_route_config', null, { method: 'GET', auth: false }); assert.equal(c.body.enabled, false); const st = await call('nextwave_v2_route_start', { script: SHORT, format: 'short' }); assert.equal(st.code, 409); const pr = await call('nextwave_v2_route_runtime_probe', null, { method: 'GET', auth: false }); assert.equal(pr.code, 404); } finally { if (old === undefined) delete process.env.VERCEL_ENV; else process.env.VERCEL_ENV = old; settings.delete('nextwave_v2_route_enabled'); } });
await t('runtime probe (preview only) reports canvas, fonts, assets, ffmpeg', async () => { const r = await call('nextwave_v2_route_runtime_probe', null, { method: 'GET', auth: false }); assert.equal(r.code, 200); assert.equal(r.body.all_ok, true, JSON.stringify(r.body.checks).slice(0, 300)); });
await t('CEO can enable the flag (only path that changes it)', async () => { const r = await call('nextwave_v2_route_set_enabled', { enabled: true }); assert.equal(r.code, 200); const c = await call('nextwave_v2_route_config', null, { method: 'GET', auth: false }); assert.equal(c.body.enabled, true); });

const runFull = async (name, script, format) => {
  const s = await call('nextwave_v2_route_start', { script, format, title: 'Test title' }); assert.equal(s.code, 200, JSON.stringify(s.body).slice(0, 200)); assert.equal(s.body.status, 'planned'); assert.equal(s.body.gate.route, 'PASS');
  for (const ch of s.body.chunks) { const c = await call('nextwave_v2_route_chunk', { build_id: s.body.build_id, index: ch.index }); assert.equal(c.code, 200, JSON.stringify(c.body)); process.stdout.write('.'); }
  const f = await call('nextwave_v2_route_finish', { build_id: s.body.build_id }); assert.equal(f.code, 200, JSON.stringify(f.body).slice(0, 300)); return { s: s.body, f: f.body };
};
console.log('\n[Short — approved script -> Brain PASS -> narration -> chunked render -> thumbnail -> QC]');
let shortRun; await t('Short: start(PASS) + chunk* + finish -> ready_for_review, 1080x1920, audio present, thumbnail stored', async () => { shortRun = await runFull('short', SHORT, 'short'); const { f } = shortRun; assert.equal(f.status, 'ready_for_review'); assert.equal(f.final.encode.width, 1080); assert.equal(f.final.encode.height, 1920); assert.ok(f.final.encode.has_audio && f.final.encode.has_video); assert.ok(Math.abs(f.final.encode.duration - f.duration_sec) < 0.8); assert.ok(f.final.post_encode_issues.length === 0); assert.ok(objects.get(`nextwave-v2-route/${f.build_id}/thumbnail.png`).slice(0, 4).toString('hex') === '89504e47'); assert.ok(objects.get(`nextwave-v2-route/${f.build_id}/final.mp4`).length > 100000); console.log(''); });
await t('Short: narration ran exactly once; Brain used recordings (2 model calls replayed); no HeyGen/Submagic/YouTube call', () => { assert.equal(calls.eleven, 1); assert.equal(calls.heygen, 0); assert.ok(!calls.other.some((x) => /heygen|submagic|youtube|googleapis/i.test(x))); });
await t('Short: idempotent — re-running start returns the planned build with no new vendor spend; chunk re-run is reused', async () => { const before = calls.eleven + calls.anthropic; const s = await call('nextwave_v2_route_start', { script: SHORT, format: 'short', title: 'Test title' }); assert.equal(s.body.reused, true); assert.equal(calls.eleven + calls.anthropic, before); });
await t('status action returns the persisted build (QC, gate, vendor) for the reviewer', async () => { const r = await call('nextwave_v2_route_status', { build_id: shortRun.f.build_id }); assert.equal(r.code, 200); assert.equal(r.body.status, 'ready_for_review'); assert.equal(r.body.qc_pre_render.ok, true); assert.equal(r.body.vendor.elevenlabs_chars, SHORT.length); });
console.log('\n[Long]');
await t('Long: start(PASS) + chunk* + finish -> ready_for_review, 1920x1080', async () => { const { f } = await runFull('long', LONG, 'long'); assert.equal(f.status, 'ready_for_review'); assert.equal(f.final.encode.width, 1920); assert.equal(f.final.encode.height, 1080); assert.ok(f.chunk_count >= 4); console.log(''); });
console.log('\n[NEEDS_REVIEW / BLOCK through the real handler — no narration, no render, no spend]');
const elevenBefore = () => calls.eleven;
await t('BLOCK-class script (Brain has no recording -> model error) stops cleanly, narration never called', async () => { const e0 = elevenBefore(); const r = await call('nextwave_v2_route_start', { script: 'This script was never recorded so the model call fails. It mentions $500 a month.', format: 'short' }); assert.equal(r.code, 200); assert.ok(['blocked', 'needs_review'].includes(r.body.status), r.body.status); assert.equal(calls.eleven, e0); assert.ok(r.body.exception); assert.ok(!r.body.chunks || r.body.chunks.length === 0); });
await t('chunk/finish on a stopped (non-planned) build are refused', async () => { const r = await call('nextwave_v2_route_start', { script: 'Another unrecorded script with 5% and $100.', format: 'short' }); const c = await call('nextwave_v2_route_chunk', { build_id: r.body.build_id, index: 0 }); assert.equal(c.code, 409); const f = await call('nextwave_v2_route_finish', { build_id: r.body.build_id }); assert.equal(f.code, 409); });
console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
